[theme]
<<<<<<< HEAD
base="dark"
primaryColor="purple"
=======
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
>>>>>>> f1492a8f4a7e9e1d8bf537f46b35805ba73f9dc0
